Lesson 19 Rack app "Time"
mubat/rack_rails_course pull request #1
Opened 2021-07-26 22:23 UTC by mubat

2021-07-27 07:22 UTC, BubuntuClu requested changes

2021-07-27 07:22 UTC, BubuntuClu commented on app.rb
> +class App
Rack приложение
Это данный класс. В его обязанности входит обработка запроса и формирование ответа в формате совместимом с rack. То есть здесь мы проверяем правильный ли пришёл URL или нужно отдать 404, хватает ли параметров или нужно отдать 400-й статус. При этом логику формирования тела ответа мы помещаем в отдельный класс бизнес логики.

Класс бизнес логики
Это отдельный простой Ruby класс, который может называться, например, TimeFormatter. Он ничего не должен знать о rack приложении, иными словами о том кто и где будет его использовать. Мы можем вызывать его из консоли или в другом Ruby приложении без HTTP API интерфейса.

2021-07-27 07:22 UTC, BubuntuClu commented on app.rb
> +    @headers = headers
зачем они описаны как инстанс переменные если они нигда не используется кроме этого метода?

2021-07-27 07:22 UTC, BubuntuClu commented on app.rb
> +  def format
где этот метод используется?

2021-07-27 07:23 UTC, BubuntuClu commented on app.rb
> +    [@status, @headers, @body]
для ответа используй Rack::Response

2021-07-27 19:01 UTC, BubuntuClu requested changes

2021-07-27 19:01 UTC, BubuntuClu commented on time_format.rb
> +    validate_formats
это запуск логики, этого не должно быть в инициализаторе. стоит вынести это в метод `call`

2021-07-27 19:01 UTC, BubuntuClu commented on time_format.rb
> +  def handle
имя метода не соотвествует тому что возвращается, вообще просто глагол обычно не встречается, с ним в паре обычно существительно идет

2021-07-27 19:01 UTC, BubuntuClu commented on app.rb
> +    @request = Rack::Request.new(env)
зачем тут инстанс переменная? передай ее явно в метод `process`

2021-07-27 19:01 UTC, BubuntuClu commented on app.rb
> +  def status
на мой взгляд это плохие методы. сделай хороший воркфлоу и в рамках этого флоу вызывай метод `make_response` и в него передавай нужный статус и текст для ответа

2021-07-27 19:01 UTC, BubuntuClu commented on app.rb
> +    @handler = @handlers[@request.path.to_sym].new(@request.params['format'])
зачем такая сложность? почему бы просто не вызвать нужный метод? сам же написал "что хотел минималистичный" код написать) а усложняешь такими конструкциями

2021-07-27 19:01 UTC, BubuntuClu commented on app.rb
> +    return unless @handlers.key?(@request.path.to_sym)
везде повторяется эта конструкция, раз не вынес в метод, то значит с логикой приложения что-то не так. зачем для каждого элемента проверять одно и тоже?

стоит пересомтреть архитекутуру кода

2021-07-27 19:01 UTC, BubuntuClu commented on time_format.rb
> +    ["Unknown time format [#{@not_support_formats.join(', ')}]\n"] unless @not_support_formats.empty?
`if errors?`
вообще странная проверка, мне кжается стоит вызывать этот метод, когда ты вызвал `timeformat.errors?` и убедился что есть ошибки

2021-07-27 19:01 UTC, BubuntuClu commented on time_format.rb
> +    format = @request_format.split(',')
ты же уже сплитил данные в `validate_formats`, а тут о5 надо сплитить? что-то не оптимально, делаешь несколько раз одно и тоже действие

рекомендую сделать метод `call` в котором за обход массива параметров ты заполнишь массив валидных форматов и невалидных форматов. далее проверкой `erorrs?/success?` определишь какой метод дернуть, метод с правильными форматами или с неправильными

2021-07-27 19:01 UTC, BubuntuClu commented on app.rb
> +    process
какой-то слишком общий нейминг для метода, не совсем понятно что происходит

2021-07-27 19:01 UTC, BubuntuClu commented on app.rb
> +  end
читая этот метод, не видна "история" которую он рассказывает. 

прикольно было бы видеть что-то типа такого(далее псеводок
```
if path.valid?
   process_params
else
  make response with 404
end


def process_params
 if tf.success?
   make response with 200, tf.time_string
 else
   make response with 400, tf.invalid_string
```

2021-07-27 19:12 UTC, mubat commented on time_format.rb
> +    validate_formats
это не запуск логики. Логика выполняется в методе `process`. `validate_formats` проверяет входящие данные

2021-07-27 19:13 UTC, mubat commented on time_format.rb
> +  def handle
Имя метода сделано в общем виде. Если добавлять 2й обработчик, то там этот метод должен быть, который обрабатывает данные и возвращает результат обработки

2021-07-27 19:14 UTC, mubat commented on app.rb
> +    @request = Rack::Request.new(env)
инстанс, чтобы в других местах можно было взять из запроса нужные данные

2021-07-27 19:16 UTC, mubat commented on app.rb
> +  def status
эти методы были предложены на лекции. Там так и было сказано: "... лучше было бы сделать методы ..."
Если есть какой-то общий шаблон построение Rack, можешь показать ссылку?

2021-07-27 19:17 UTC, mubat commented on app.rb
> +    @handler = @handlers[@request.path.to_sym].new(@request.params['format'])
Таким образом можно кучу обработчиков добавить. Достаточно указать их в хеше.

2021-07-27 19:18 UTC, mubat commented on app.rb
> +    return unless @handlers.key?(@request.path.to_sym)
Мне на ум приходит только обработчик, который будет формировать ответ в зависимости от статуса запроса. Но ты сказал, что он не должен знать про Rack

2021-07-27 19:19 UTC, mubat commented on time_format.rb
> +    ["Unknown time format [#{@not_support_formats.join(', ')}]\n"] unless @not_support_formats.empty?
Это на случай, если нужно будет другие ошибки выводить, когда будут другие условия для неё

2021-07-27 19:21 UTC, mubat commented on time_format.rb
> +    format = @request_format.split(',')
> ты же уже сплитил данные в validate_formats, а тут о5 надо сплитить?
Это сделано для разделения функционала. Здесь это делается для одних целей, там - для других. Если Делать вместе, то расширять такой код будет труднее.

2021-07-27 19:22 UTC, mubat commented on app.rb
> +    process
В этом из задумка - сделать общий нейминг для всех обработчиков (если такие будут)

2021-07-27 19:24 UTC, mubat commented on app.rb
> +  end
Это тут зачем, когда есть отдельный метод для формирования кода ответа?
У тебя здесь сразу 2 логических действия: формирование тела ответа и кода ответа. Я же разделил их, как было предложено на лекции

2021-07-28 07:04 UTC, BubuntuClu requested changes

2021-07-28 07:04 UTC, BubuntuClu commented on app.rb
> +  end
тут идет разделение логики на уровне процесса обработки запроса. ты разделяешь логику где тебя надо обработать запрос и где не надо

для формирования ответа отдельный метод, который будет использоваться в 3ех местах

2021-07-28 07:04 UTC, BubuntuClu commented on app.rb
> +  def initialize_response_arguments
зачем этот метод нужен? у тебя как минимум есть инициалайзер, где это можно поместить этот код. вообще это задание можно сделать без использования инстанс переменных, я не вижу смысла их тут использовать. используй параметры у методов и передавай явно то что тебе нужно

2021-07-28 07:04 UTC, BubuntuClu commented on handler_time_format.rb
> +    validate_formats
тут остается тоже самое. не помещают в инициализацию метод расчета логики. либо пиши тут какую-то логику(что плохо) либо отдельным вызовом метода это делай

2021-07-28 07:04 UTC, BubuntuClu commented on app.rb
> +    @status = 400 if handler.errors?
`if handler.errors?`
`@body = handler.errors?`
у тебя две подряд одинаковые проверки, в чем смысл? может их в одну ветку if разместить?

2021-07-28 07:04 UTC, BubuntuClu commented on app.rb
> +    @request = Rack::Request.new(env)
а почему бы параметром не передать?

2021-07-28 12:27 UTC, BubuntuClu commented on app.rb
> +    handler.handle
рабочий.работать)

2021-07-28 12:27 UTC, BubuntuClu commented on handler_time_format.rb
> +  def initialize(format)
тут format и метод format. не хорошо так делать

2021-07-28 12:27 UTC, BubuntuClu commented on handler_time_format.rb
> +    @request_format = format.split(',')
тут в итоге кто сплититься? входные данные или результат метода?

2021-07-28 12:27 UTC, BubuntuClu commented on handler_base.rb
> +# frozen_string_literal: true
не вижу большойго смысла в этом классе. почему бы это не оставить в HandlerTimeFormat?

2021-07-28 12:45 UTC, mubat commented on handler_base.rb
> +# frozen_string_literal: true
это не я. Это всё рубокоп, порядки свои тут наводит )

2021-07-28 15:08 UTC, merged